= Features

Some features, which exists in jrsonnet, but not yet in other implementations.

Any of those features may be enabled during build time using feature flags, i.e: `--features=exp-destruct`.

== `exp-destruct`

Destructuring assignment, upstream issue: https://github.com/google/jsonnet/issues/307

Destructuring object:

[source,jsonnet]
----
local {a: b} = obj; ...
// Same as
local b = obj.a; ...
----

Field name may be omitted:

> However, field name omission looks off here, as currently jsonnet doesn't allows `local a = 1; {a}`
as a sugar for `local a = 1; {a: a}`, this causing asymmetry

[source,jsonnet]
----
local {a} = obj; ...
// Same as
local a = obj.a; ...
----

Rest of fields may be collected into another object:

[source,jsonnet]
----
local {a, ...rest} = obj; ...
----

And it is possible to set field defaults:

[source,jsonnet]
----
local {a = 1} = {};

a == 1
----

Destructuring arrays:

[source,jsonnet]
----
local [a, b, c] = array; ...
----

Rest of fields in any position may be collected into other array:

[source,jsonnet]
----
local [...rest, a] = array; ...
local [a, ...rest] = array; ...
local [a, ...rest, b] = array; ...
----

In case of not needed fields there is `?` (because `_` is not reserved):

[source,jsonnet]
----
local [?, b, c] = ["a", "b", "c"]; ...
----

Recursive destructuring also works:

[source,jsonnet]
----
local {a: [{b: {c: d}}]} = {a:[{b:{c:5}}]}; d == 5
----

Also, mutually recursive declaration works:

[source,jsonnet]
----
local
  {a, b, c} = {a: y, b: c, c: x},
  {x, y, z} = {x: a, y: 2, z: b};
z == 2
----

This feature also works in function arguments:
> It is impossible to reference those parameters using named argument syntax

[source,jsonnet]
----
local myFun({a, b, c}) = a + b + c;

myFun({a: 1, b: 2, c: 3})
----

== `--preserve-order`

Object field order preservation during manifestification, upstream issue: https://github.com/google/jsonnet/issues/903

This is a global CLI flag: `--preserve-order`.
When enabled, all object field iteration (including manifestification and `std.objectFields*`) preserves declaration order instead of sorting alphabetically.

[source,bash]
----
jrsonnet --preserve-order input.jsonnet
----

Example behavior:

[source,jsonnet]
----
// Without --preserve-order:
std.objectFields({c: 1, b: 2, a: 3}) == ['a', 'b', 'c']  // Fields are sorted

// With --preserve-order:
std.objectFields({c: 1, b: 2, a: 3}) == ['c', 'b', 'a']  // Fields preserve declaration order
----

== `exp-object-iteration`

Iteration over object fields in comprehensions, upstream issue: https://github.com/google/jsonnet/issues/543

This feature is not implemented as proposed in upstream, it only yields `[key, value]` arrays per element:

[source,jsonnet]
----
{
    [i[0] + '!']: i[1] + '!'
    for i in {
        a: 1,
        b: 2,
        c: 3,
    }
} == {
    'a!': '1!',
    'b!': '2!',
    'c!': '3!',
}
----

However, it may be combined with `exp-destruct`, to implement syntax close to proposed:

[source,jsonnet]
----
{
    [k + '!']: v + '!'
    for [k, v] in {
        a: 1,
        b: 2,
        c: 3,
    }
} == {
    'a!': '1!',
    'b!': '2!',
    'c!': '3!',
}
----

When `--preserve-order` is enabled globally, object iteration in comprehensions also preserves declaration order.

== `exp-null-coalescing`

Provides a new operator and new indexing syntax sugar:

`a ?? b` - equivalent to `if a == null then b else a`

`a?.b`, `a?.['b']` - equivalent to `if a != null then std.get(a, 'b', null)`
